# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest    

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Install PHP
      uses: shivammathur/setup-php@1.4.3
      with:
        php-version: 7.4
        extension-csv: pdo, pdo_mysql

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # dépendances composer
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    # PHPStan
    - name: PHPStan
      uses: chindit/actions-phpstan@master
      with:
          # Arguments to add to PHPStan
          arguments: 'src/ --level=7'
        
        
